# coding: utf-8
# Form implementation generated from reading ui file 'MainGui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(519, 238)
        Form.setStyleSheet("QWidget{\n"
"    background-color:#22222D;\n"
"}\n"
"QPushButton{\n"
"    background-color:#22222e;\n"
"    width:24px;\n"
"    height:27px;\n"
"    color:white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:#2D0B0B;\n"
"color:#0659A9;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:#FA1200;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:#22222e;\n"
"border: 3px solid #C40000;\n"
"border-radius:10;\n"
"color:white;\n"
"}\n"
"QListWidget{\n"
"color:white;\n"
"\n"
"}\n"
"\n"
"")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 331, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.corx = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.corx.setObjectName("corx")
        self.gridLayout.addWidget(self.corx, 0, 1, 1, 1)
        self.movem = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.movem.setObjectName("movem")
        self.gridLayout.addWidget(self.movem, 0, 0, 1, 1)
        self.slep = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.slep.setObjectName("slep")
        self.gridLayout.addWidget(self.slep, 2, 0, 1, 1)
        self.click1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.click1.setObjectName("click1")
        self.gridLayout.addWidget(self.click1, 1, 1, 1, 1)
        self.hok2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hok2.setStyleSheet("QPushButton{\n"
"    background-color:#F07427;\n"
"    color:#C8C8C8;\n"
"    width:24px;\n"
"    height:27px;\n"
"}\n"
"")
        self.hok2.setText("")
        self.hok2.setObjectName("hok2")
        self.gridLayout.addWidget(self.hok2, 3, 2, 1, 1)
        self.tine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tine.setObjectName("tine")
        self.gridLayout.addWidget(self.tine, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.cory = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cory.setObjectName("cory")
        self.gridLayout.addWidget(self.cory, 0, 2, 1, 1)
        self.click = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.click.setStyleSheet("")
        self.click.setObjectName("click")
        self.gridLayout.addWidget(self.click, 1, 0, 1, 1)
        self.hok1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hok1.setObjectName("hok1")
        self.gridLayout.addWidget(self.hok1, 3, 1, 1, 1)
        self.listwidget = QtWidgets.QListWidget(Form)
        self.listwidget.setGeometry(QtCore.QRect(340, 10, 171, 151))
        self.listwidget.setStyleSheet("background-color:#2D1325;")
        self.listwidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listwidget.setUniformItemSizes(False)
        self.listwidget.setWordWrap(False)
        self.listwidget.setSelectionRectVisible(False)
        self.listwidget.setObjectName("listwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 160, 171, 47))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.clear.setObjectName("clear")
        self.horizontalLayout.addWidget(self.clear)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(110, 210, 291, 23))
        self.pushButton.setStyleSheet("background-color: #2D2222;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AdminKM"))
        self.corx.setPlaceholderText(_translate("Form", " X"))
        self.movem.setText(_translate("Form", "Move mouse"))
        self.slep.setText(_translate("Form", "Sleep"))
        self.tine.setPlaceholderText(_translate("Form", " Seconds"))
        self.pushButton_2.setText(_translate("Form", "Hot Key Click"))
        self.cory.setPlaceholderText(_translate("Form", " Y"))
        self.click.setText(_translate("Form", "Click key"))
        self.listwidget.setSortingEnabled(False)
        self.clear.setText(_translate("Form", "Clear"))
        self.pushButton.setText(_translate("Form", "Start"))
